apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-task-deployment
  namespace: task  
  labels:
    app: frontend-task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-task
  template:
    metadata:
      labels:
        app: frontend-task
    spec:
      containers:
      - name: frontend-task
        image: task-manager-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80

