apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: task

type: Opaque

data:
  DB_HOST: bXlzcWwtc2VydmljZQ==
  DB_PORT: MzMwNg==
  DB_NAME: dGFza2Ri
  DB_USER: dGFza3VzZXI=
  DB_PASSWORD: dGFza3Bhc3N3b3Jk
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
