
name: Task Manager CI

on:
  push:
    branches:
      - main
     

  pull_request:
    branches:
      - main

jobs:

  backend:

    name: Backend Tests

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Python Syntax
        run: |
          python -m py_compile app.py

      - name: Build Backend Docker Image
        run: |
          docker build -t task-manager-backend .



  frontend:

    name: Frontend Checks

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Frontend Docker Image
        run: |
          docker build -t task-manager-frontend .



  docker-compose:

    name: Validate Docker Compose

    runs-on: ubuntu-latest

    needs:
      - backend
      - frontend

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Validate Compose File
        run: docker compose config

      - name: Build Services
        run: docker compose build